# Generated by Django 3.2 on 2021-04-30 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tran_id', models.CharField(max_length=15)),
                ('val_id', models.CharField(max_length=75)),
                ('card_type', models.CharField(max_length=150)),
                ('store_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_no', models.CharField(max_length=55, null=True)),
                ('bank_tran_id', models.CharField(max_length=155, null=True)),
                ('status', models.CharField(max_length=55)),
                ('tran_date', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
                ('card_issuer', models.CharField(max_length=255)),
                ('card_brand', models.CharField(max_length=15)),
                ('card_issuer_country', models.CharField(max_length=55)),
                ('card_issuer_country_code', models.CharField(max_length=55)),
                ('currency_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('verify_sign', models.CharField(max_length=155)),
                ('verify_sign_sha2', models.CharField(max_length=255)),
                ('risk_level', models.CharField(max_length=15)),
                ('risk_title', models.CharField(max_length=25)),
                ('reason', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
