# Generated by Django 3.2 on 2021-05-05 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='expensive_to_buy',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='img',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='is_discount',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='sold',
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=5)),
                ('sold', models.CharField(blank=True, max_length=5)),
                ('expensive_to_buy', models.CharField(blank=True, max_length=5)),
                ('selling_price', models.CharField(max_length=5)),
                ('discount', models.CharField(max_length=2)),
                ('is_discount', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.productmodel')),
            ],
        ),
    ]
