# Generated by Django 3.2 on 2021-05-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20210505_2041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='VariationModel',
        ),
    ]
