# Generated by Django 3.2 on 2021-05-06 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_variation_variationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationmodel',
            name='color',
            field=models.CharField(default=datetime.datetime(2021, 5, 6, 3, 31, 17, 431598, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variationmodel',
            name='size',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
