# Generated by Django 3.2 on 2021-05-08 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20210506_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationmodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Shop.productcategorymodel'),
            preserve_default=False,
        ),
    ]
